language: C

install: true

group: "stable"

script: echo Travis

stage: build

branches:
  only:
    - master

jobs:
  stage: build
  script:
   - make -C hello/ clean all
  stage: test
  script: 
   - make -C hello/ clean tests

